pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = "srinivasedugutta"
        IMAGE_NAME = "devops-app"
    }

    stages {
        stage("Checkout Code") {
            steps {
                git branch: "main", url: "https://github.com/srinivasedugutta/devops-scripts.git"
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    def image = docker.build("${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest", "docker/app")
                }
            }
        }

        stage("Push to DockerHub") {
            steps {
                script {
                    docker.withRegistry("https://index.docker.io/v1/", "dockerhub-login") {
                        sh "docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Docker image pushed successfully!"
        }
        failure {
            echo "Docker build/push failed!"
        }
    }
}
